services:
  fastapi:
    build: .
    restart: "unless-stopped"
    env_file:
      - .env
    ports:
      - "9080:80"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      - network

  db:
    image: postgres:16
    restart: "unless-stopped"
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  pg_admin:
    image: dpage/pgadmin4:latest
    restart: "unless-stopped"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "9081:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - network
    depends_on:
      db:
        condition: service_healthy
        restart: true

volumes:
  db_data:
  pgadmin-data:

networks:
  network: