PROJECTS_SEED = {
    "42cursus-dslr": {
        "xp": 0,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
    },
	"42cursus-darkly": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"bornNoneberoot": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"4Nonecursus-ft_linear_regression": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"work-experience-i-work-experience-i-peer-video": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"work-experience-i": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"work-experience-i-work-experience-i-company-final-evaluation": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"data-science-2": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"data-science-1": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"data-science-0": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"piscine-data-science": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"work-experience-i-work-experience-i-company-mid-evaluation": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"work-experience-i-work-experience-i-duration": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"work-experience-i-work-experience-i-contract-upload": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"exam-rank-06": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"exam-rank-05": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"ft_transcendence": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"webserv": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"cpp-module-09": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"cpp-module-08": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"cpp-module-07": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"cpp-module-06": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"inception": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"cpp-module-05": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"cpp-module-04": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"cpp-module-03": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"cpp-module-02": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"cpp-module-01": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"cpp-module-00": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
	"netpractice": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_weeks": None,
	},
}

