from models import (
	BlocEnum, 
	ProjectStatusEnum, 
	PatternsEnum,
	CategoryEnum,
	SkillsGapStatusEnum,
	SkillTypeEnum,
	ContactStatus,
)

PROJECTS_SEED = {
    "42cursus-dslr": {
        "xp": 6000,
        "bloc": BlocEnum.ai,
        "order_priority": 1,
        "estimated_hours": None,
    },
	"42cursus-darkly": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"born2beroot": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"42cursus-ft_linear_regression": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"work-experience-i-work-experience-i-peer-video": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"work-experience-i": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"work-experience-i-work-experience-i-company-final-evaluation": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"data-science-2": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"data-science-1": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"data-science-0": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"piscine-data-science": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"work-experience-i-work-experience-i-company-mid-evaluation": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"work-experience-i-work-experience-i-duration": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"work-experience-i-work-experience-i-contract-upload": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"exam-rank-06": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"exam-rank-05": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"ft_transcendence": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"webserv": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"cpp-module-09": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"cpp-module-08": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"cpp-module-07": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"cpp-module-06": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"inception": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"cpp-module-05": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"cpp-module-04": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"cpp-module-03": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"cpp-module-02": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"cpp-module-01": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"cpp-module-00": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"netpractice": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"exam-rank-04": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"cub3d": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"42cursus-minishell": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"exam-rank-03": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"42cursus-philosophers": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"exam-rank-02": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"pipex": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"so_long": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"42cursus-push_swap": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"42cursus-get_next_line": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"42cursus-ft_printf": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	},
	"42cursus-libft": {
		"xp": None,
        "bloc": None,
        "order_priority": None,
        "estimated_hours": None,
	}
}


